/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomItem: typeof import('./src/components/BottomItem.vue')['default']
    ContentItem: typeof import('./src/components/ContentItem.vue')['default']
    HeadComponent: typeof import('./src/components/headComponent.vue')['default']
    HeadItem: typeof import('./src/components/HeadItem.vue')['default']
    ModalTextItem: typeof import('./src/components/ModalTextItem.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NFlex: typeof import('naive-ui')['NFlex']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const BottomItem: typeof import('./src/components/BottomItem.vue')['default']
  const ContentItem: typeof import('./src/components/ContentItem.vue')['default']
  const HeadComponent: typeof import('./src/components/headComponent.vue')['default']
  const HeadItem: typeof import('./src/components/HeadItem.vue')['default']
  const ModalTextItem: typeof import('./src/components/ModalTextItem.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NButtonGroup: typeof import('naive-ui')['NButtonGroup']
  const NCard: typeof import('naive-ui')['NCard']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDatePicker: typeof import('naive-ui')['NDatePicker']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDrawer: typeof import('naive-ui')['NDrawer']
  const NDrawerContent: typeof import('naive-ui')['NDrawerContent']
  const NFlex: typeof import('naive-ui')['NFlex']
  const NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NIconWrapper: typeof import('naive-ui')['NIconWrapper']
  const NInput: typeof import('naive-ui')['NInput']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NModal: typeof import('naive-ui')['NModal']
  const NSpace: typeof import('naive-ui')['NSpace']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}