/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomItem: typeof import('./src/components/BottomItem.vue')['default']
    ContentItem: typeof import('./src/components/ContentItem.vue')['default']
    HeadItem: typeof import('./src/components/HeadItem.vue')['default']
    MdContenItem: typeof import('./src/components/MdContenItem.vue')['default']
    MdContentem: typeof import('./src/components/mdContentem.vue')['default']
    MdContentItem: typeof import('./src/components/mdContentItem.vue')['default']
    ModalContentItem: typeof import('./src/components/ModalContentItem.vue')['default']
    ModalTextItem: typeof import('./src/components/ModalTextItem.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const BottomItem: typeof import('./src/components/BottomItem.vue')['default']
  const ContentItem: typeof import('./src/components/ContentItem.vue')['default']
  const HeadItem: typeof import('./src/components/HeadItem.vue')['default']
  const MdContenItem: typeof import('./src/components/MdContenItem.vue')['default']
  const MdContentem: typeof import('./src/components/mdContentem.vue')['default']
  const MdContentItem: typeof import('./src/components/mdContentItem.vue')['default']
  const ModalContentItem: typeof import('./src/components/ModalContentItem.vue')['default']
  const ModalTextItem: typeof import('./src/components/ModalTextItem.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDatePicker: typeof import('naive-ui')['NDatePicker']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDivider: typeof import('naive-ui')['NDivider']
  const NDrawer: typeof import('naive-ui')['NDrawer']
  const NDrawerContent: typeof import('naive-ui')['NDrawerContent']
  const NFlex: typeof import('naive-ui')['NFlex']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NIconWrapper: typeof import('naive-ui')['NIconWrapper']
  const NImage: typeof import('naive-ui')['NImage']
  const NInput: typeof import('naive-ui')['NInput']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NModal: typeof import('naive-ui')['NModal']
  const NRadioButton: typeof import('naive-ui')['NRadioButton']
  const NRadioGroup: typeof import('naive-ui')['NRadioGroup']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NSwitch: typeof import('naive-ui')['NSwitch']
  const NText: typeof import('naive-ui')['NText']
  const NUpload: typeof import('naive-ui')['NUpload']
  const NUploadDragger: typeof import('naive-ui')['NUploadDragger']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}